# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: GoCortexIO
"""
Pack Unit Test Module

Runs a pack's integration and script unit tests the way the official
demisto/content pipeline does, so a pack that passes validation here does not
then fail the pipeline's test run.

The pipeline runs pytest with the support files staged beside the code under
test: demistomock.py, CommonServerPython.py, DemistoClassApiModule.py (which
CommonServerPython imports unconditionally), and a conftest.py whose autouse
fixtures fail any test that writes to stdout or stderr, or logs at WARNING or
above. demisto-sdk does not ship those files (it copies them from a content
checkout, which a Spellbook instance does not have), so they are vendored in
spellbook/assets/pytest_env; see the PROVENANCE.md there.

CommonServerUserPython is different again: integration code imports it
unconditionally, but no such file exists upstream to vendor, so an empty one
is generated. See GENERATED_STUBS below.

Tests run against a copy of the package in a temporary sandbox rather than in
the pack itself, so the user's content is never left carrying the scaffolding
or a __pycache__ directory.
"""

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import click


PYTEST_ENV_DIR = Path(__file__).parent / "assets" / "pytest_env"

# Staged beside the code under test, matching the pipeline's copy_files step.
# DemistoClassApiModule is not optional: CommonServerPython ends with an
# unconditional `from DemistoClassApiModule import *`, so omitting it makes
# every `from CommonServerPython import *` raise ModuleNotFoundError, which
# is every integration test there is.
SCAFFOLDING = (
    "demistomock.py",
    "CommonServerPython.py",
    "DemistoClassApiModule.py",
    "conftest.py",
)

# Not vendored, because there is nothing upstream to vendor: this file does
# not exist in demisto/content at any path. It is the user-customisation hook,
# generated empty and gitignored in a content checkout, and integration code
# imports it unconditionally (`from CommonServerUserPython import *`). An
# empty module is what the real environment provides when a pack adds no
# customisations, so an empty module is what the sandbox stages.
GENERATED_STUBS = ("CommonServerUserPython.py",)

GENERATED_STUB_BODY = (
    "# Generated by spellbook for the test sandbox. The real environment\n"
    "# provides this module empty unless the pack supplies its own.\n"
)

# Content types whose packages carry Python unit tests.
TESTABLE_CONTENT_DIRS = ("Integrations", "Scripts")

TEST_FILE_SUFFIX = "_test.py"

# pytest exit codes. 1 means tests ran and failed, which is a statement about
# the pack. 2 (interrupted, which is where a collection error lands) and 3
# (internal error) mean nothing was executed, which is a statement about the
# harness. Conflating them is how a real test failure hides: a pack with
# perfect tests and a pack with broken ones produce the same line.
PYTEST_INTERRUPTED = 2
PYTEST_INTERNAL_ERROR = 3

MISSING_MODULE_PATTERN = re.compile(r"ModuleNotFoundError: No module named '([^']+)'")

# A pack's suite should be quick. The cap stops a hanging test from wedging
# validation with no output.
TEST_TIMEOUT_SECONDS = 600


def find_testable_packages(pack_path: Path) -> list[Path]:
    """Return package directories that contain at least one unit test."""
    packages = []
    for content_type in TESTABLE_CONTENT_DIRS:
        content_dir = pack_path / content_type
        if not content_dir.is_dir():
            continue
        for package in sorted(content_dir.iterdir()):
            if not package.is_dir() or package.is_symlink():
                continue
            if any(package.glob(f"*{TEST_FILE_SUFFIX}")):
                packages.append(package)
    return packages


def _stage_sandbox(package: Path, sandbox: Path) -> None:
    """Copy the package, the vendored scaffolding and the generated stubs."""
    shutil.copytree(package, sandbox, dirs_exist_ok=True)
    for name in SCAFFOLDING:
        source = PYTEST_ENV_DIR / name
        if source.exists():
            shutil.copyfile(source, sandbox / name)

    # Only when the package does not ship its own: a pack may legitimately
    # carry real customisations in CommonServerUserPython.
    for name in GENERATED_STUBS:
        stub = sandbox / name
        if not stub.exists():
            stub.write_text(GENERATED_STUB_BODY, encoding="utf-8")


def run_pack_tests(pack_path: Path) -> bool:
    """Run unit tests for every testable package in the pack.

    Packs with no unit tests pass immediately, which is the common case for
    XSIAM content. Missing scaffolding is reported and skipped rather than
    failing, matching how a missing demisto-sdk or ruff is handled.

    Args:
        pack_path: Path to the pack directory.

    Returns:
        True if every package passed (or there was nothing to run).
    """
    packages = find_testable_packages(pack_path)
    if not packages:
        return True

    missing = [name for name in SCAFFOLDING if not (PYTEST_ENV_DIR / name).exists()]
    if missing:
        click.echo(
            f"[WARN] pytest scaffolding missing ({', '.join(missing)}), "
            f"skipping unit tests"
        )
        return True

    passed = True
    for package in packages:
        if not _run_package_tests(pack_path, package):
            passed = False
    return passed


def _harness_failure_reason(output: str) -> str:
    """Name the missing dependency behind a collection failure, if identifiable.

    A bare "could not run" sends the reader looking at their own tests. Naming
    the module points at the harness, which is where the fix belongs.
    """
    match = MISSING_MODULE_PATTERN.search(output)
    if match:
        return f" (harness dependency missing: {match.group(1)})"
    return ""


def _run_package_tests(pack_path: Path, package: Path) -> bool:
    """Run one package's tests in a sandbox, returning True if they passed."""
    workdir = Path(tempfile.mkdtemp(prefix="spellbook_tests_"))
    sandbox = workdir / package.name
    try:
        _stage_sandbox(package, sandbox)

        env = os.environ.copy()
        # The sandbox holds demistomock and CommonServerPython, which the
        # code under test imports by bare name.
        env["PYTHONPATH"] = str(sandbox)
        env["PYTHONDONTWRITEBYTECODE"] = "1"

        try:
            result = subprocess.run(
                [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "."],
                cwd=str(sandbox),
                env=env,
                capture_output=True,
                text=True,
                timeout=TEST_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired:
            click.echo(
                f"[ERROR] {pack_path.name}: unit tests for {package.name} exceeded "
                f"{TEST_TIMEOUT_SECONDS}s and were stopped"
            )
            return False
        except FileNotFoundError:
            click.echo("[WARN] pytest not found, skipping unit tests")
            return True

        if result.returncode == 0:
            return True

        if result.stdout:
            click.echo(result.stdout, nl=False)
        if result.stderr:
            click.echo(result.stderr, nl=False)

        if result.returncode in (PYTEST_INTERRUPTED, PYTEST_INTERNAL_ERROR):
            reason = _harness_failure_reason(result.stdout + result.stderr)
            click.echo(
                f"[ERROR] {pack_path.name}: unit tests could NOT RUN for "
                f"{package.name}{reason} - the harness failed before executing "
                f"any test, so this says nothing about the pack's tests"
            )
            return False

        click.echo(
            f"[ERROR] {pack_path.name}: unit tests failed for {package.name} "
            f"(the official content pipeline runs these same tests)"
        )
        return False
    finally:
        shutil.rmtree(workdir, ignore_errors=True)
